# Generated by Django 4.2.7 on 2025-11-09 22:28

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_geojson', models.TextField(help_text='GeoJSON polygon data')),
                ('polygon_geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='PostGIS polygon geometry', srid=4326)),
                ('cities_count', models.IntegerField(help_text='Number of cities found in polygon')),
                ('total_population', models.BigIntegerField(help_text='Total population in polygon')),
                ('average_population', models.FloatField(help_text='Average population in polygon')),
                ('area_analyzed_km2', models.FloatField(help_text='Area of polygon in square kilometers')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_duration_ms', models.IntegerField(help_text='Query execution time in milliseconds')),
            ],
            options={
                'verbose_name': 'Polygon Analysis',
                'verbose_name_plural': 'Polygon Analyses',
                'ordering': ['-analysis_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('total_searches', models.IntegerField(default=0)),
                ('total_cities_found', models.IntegerField(default=0)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('min_latitude', models.FloatField(blank=True, null=True)),
                ('max_latitude', models.FloatField(blank=True, null=True)),
                ('min_longitude', models.FloatField(blank=True, null=True)),
                ('max_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Search Session',
                'verbose_name_plural': 'Search Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=100)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('population', models.IntegerField(help_text='City population')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('description', models.TextField(blank=True, help_text='City description', null=True)),
                ('founded_year', models.IntegerField(blank=True, help_text='Year founded', null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, help_text='City area in square kilometers', max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Time zone identifier (e.g., Europe/London)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location as Point', srid=4326)),
                ('elevation_m', models.IntegerField(blank=True, help_text='Elevation above sea level in meters', null=True)),
                ('gdp_per_capita', models.DecimalField(blank=True, decimal_places=2, help_text='GDP per capita in USD', max_digits=10, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, help_text='Unemployment rate as percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('city_type', models.CharField(choices=[('capital', 'Capital City'), ('major', 'Major City'), ('medium', 'Medium City'), ('small', 'Small City'), ('town', 'Town')], default='medium', help_text='City classification by size', max_length=20)),
                ('data_source', models.CharField(default='manual_entry', help_text='Source of the city data', max_length=100)),
            ],
            options={
                'verbose_name': 'Advanced City',
                'verbose_name_plural': 'Advanced Cities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['population'], name='advanced_js_populat_1f1af0_idx'), models.Index(fields=['country'], name='advanced_js_country_044a1e_idx'), models.Index(fields=['city_type'], name='advanced_js_city_ty_f2c8ae_idx')],
            },
        ),
    ]
