# Generated by Django 4.2.7 on 2025-10-20 20:17

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('region_code', models.CharField(max_length=10, unique=True)),
                ('region_type', models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('county', 'County'), ('municipality', 'Municipality'), ('district', 'District')], max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area_km2', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('perimeter_km', models.FloatField(blank=True, null=True)),
                ('total_population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('population_year', models.IntegerField(default=2023)),
                ('population_density', models.FloatField()),
                ('urban_population_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gdp_total', models.FloatField(blank=True, null=True)),
                ('gdp_per_capita', models.FloatField(blank=True, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('agricultural_area_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('forest_area_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('urban_area_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('admin_level', models.IntegerField(default=1)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'db_table': 'regions_region',
                'indexes': [models.Index(fields=['country'], name='regions_reg_country_9e3f5f_idx'), models.Index(fields=['region_type'], name='regions_reg_region__c3e806_idx'), models.Index(fields=['total_population'], name='regions_reg_total_p_0d0154_idx'), models.Index(fields=['area_km2'], name='regions_reg_area_km_069dac_idx')],
                'unique_together': {('name', 'country', 'region_type')},
            },
        ),
    ]
