# Generated by Django 4.2.7 on 2025-09-21 22:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrishCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countyname', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Irish County',
                'verbose_name_plural': 'Irish Counties',
                'db_table': 'irish_counties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('highway', 'Highway'), ('railway', 'Railway'), ('waterway', 'Waterway'), ('airway', 'Airway')], max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'Transportation Route',
                'verbose_name_plural': 'Transportation Routes',
                'db_table': 'transportation_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EuropeanCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'European City',
                'verbose_name_plural': 'European Cities',
                'db_table': 'european_cities',
                'ordering': ['-population'],
                'managed': True,
            },
        ),
    ]
