# Generated by Django 4.2.7 on 2025-09-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='europeancity',
            options={'managed': False, 'ordering': ['-population'], 'verbose_name': 'European City', 'verbose_name_plural': 'European Cities'},
        ),
    ]
