# Generated by Django 4.2.7 on 2025-10-05 20:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-population'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='cities_api__country_7ddc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='cities_api__is_capi_e3d8a0_idx',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='elevation_m',
        ),
        migrations.RemoveField(
            model_name='city',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates', srid=4326),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='cities_api__name_17129a_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='cities_api__country_1686d9_idx'),
        ),
    ]
