# Generated by Django 4.2.7 on 2025-10-20 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('city_type', models.CharField(choices=[('capital', 'Capital City'), ('major', 'Major City'), ('regional', 'Regional City'), ('town', 'Town')], default='town', max_length=20)),
                ('urban_area_km2', models.FloatField(blank=True, null=True)),
                ('population_density', models.FloatField(blank=True, null=True)),
                ('gdp_per_capita', models.IntegerField(blank=True, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('green_space_percentage', models.FloatField(blank=True, null=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('population_year', models.IntegerField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cities_city',
                'indexes': [models.Index(fields=['country'], name='cities_city_country_6d703a_idx'), models.Index(fields=['city_type'], name='cities_city_city_ty_d8bb32_idx'), models.Index(fields=['population'], name='cities_city_populat_ca51b0_idx')],
                'unique_together': {('name', 'country')},
            },
        ),
    ]
